name: CI
on:
  push:
    branches:
      - main
permissions: write-all
env:
  BRANCH: 1.0.3
jobs:
  split-upm:
    name: split "$BRANCH" branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Split
        run: |
          git subtree split -P "$PKG_ROOT" -b "$BRANCH"
          git push -u -f origin "$BRANCH"
        env:
          PKG_ROOT: Assets/DreamsimPackageRoot
