name: CI
on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Split
        run: |
          git subtree split -P "$PKG_ROOT" -b upm
          git push -u origin upm
        env:
          PKG_ROOT: Assets/DreamsimPackageRoot
